name: commander
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  crossplat_objectid:

dev_dependencies:
  test:

dependency_overrides:
  dscript_exec:
    path: ../../dart/dscript_exec
